/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uiObjects;

import java.awt.Color;
import javax.swing.JTextArea;

/**
 *
 * @author Daan van der Spek
 */
public class singleVU extends javax.swing.JPanel {
    public JTextArea[] areas = new JTextArea[12];
    /**
     * Creates new form singleVU
     */
    public singleVU() {
        initComponents();
        areas = new JTextArea[] {ta1, ta2, ta3, ta4, ta5, ta6, ta7, ta8, ta9, ta10, ta11, ta12};
    }

    public void setValue(int value){
        Color red = new Color(254,0,0);
        Color yellow = new Color(255,242,0);
        Color green = new Color(0,255,1);
        Color grey = new Color(195,195,195);
        
        if(value>=0x0c){
            areas[11].setBackground(red);
        } else {
            areas[11].setBackground(grey);
        }
        if(value>=0x0b){
            areas[10].setBackground(yellow);
        } else {
            areas[10].setBackground(grey);
        }
        if(value>=0x0a){
            areas[9].setBackground(yellow);
        } else {
            areas[9].setBackground(grey);
        }
        if(value>=0x09){
            areas[8].setBackground(yellow);
        } else {
            areas[8].setBackground(grey);
        }
        if(value>=0x08){
            areas[7].setBackground(green);
        } else {
            areas[7].setBackground(grey);
        }
        if(value>=0x07){
            areas[6].setBackground(green);
        } else {
            areas[6].setBackground(grey);
        }
        if(value>=0x06){
            areas[5].setBackground(green);
        } else {
            areas[5].setBackground(grey);
        }
        if(value>=0x05){
            areas[4].setBackground(green);
        } else {
            areas[4].setBackground(grey);
        }
        if(value>=0x04){
            areas[3].setBackground(green);
        } else {
            areas[3].setBackground(grey);
        }
        if(value>=0x03){
            areas[2].setBackground(green);
        } else {
            areas[2].setBackground(grey);
        }
        if(value>=0x02){
            areas[1].setBackground(green);
        } else {
            areas[1].setBackground(grey);
        }
        if(value>=0x01){
            areas[0].setBackground(green);
        } else {
            areas[0].setBackground(grey);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ta12 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta11 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta10 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta9 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta8 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta7 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        ta3 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        ta6 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        ta5 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        ta4 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        ta2 = new javax.swing.JTextArea();

        ta12.setEditable(false);
        ta12.setBackground(new java.awt.Color(204, 204, 204));
        ta12.setColumns(1);
        ta12.setFont(new java.awt.Font("Monospaced", 0, 3)); // NOI18N
        ta12.setRows(1);
        ta12.setTabSize(1);
        jScrollPane1.setViewportView(ta12);

        ta11.setEditable(false);
        ta11.setBackground(new java.awt.Color(204, 204, 204));
        ta11.setColumns(1);
        ta11.setFont(new java.awt.Font("Monospaced", 0, 3)); // NOI18N
        ta11.setRows(1);
        ta11.setTabSize(1);
        jScrollPane2.setViewportView(ta11);

        ta10.setEditable(false);
        ta10.setBackground(new java.awt.Color(204, 204, 204));
        ta10.setColumns(1);
        ta10.setFont(new java.awt.Font("Monospaced", 0, 3)); // NOI18N
        ta10.setRows(1);
        ta10.setTabSize(1);
        jScrollPane3.setViewportView(ta10);

        ta9.setEditable(false);
        ta9.setBackground(new java.awt.Color(204, 204, 204));
        ta9.setColumns(1);
        ta9.setFont(new java.awt.Font("Monospaced", 0, 3)); // NOI18N
        ta9.setRows(1);
        ta9.setTabSize(1);
        jScrollPane4.setViewportView(ta9);

        ta8.setEditable(false);
        ta8.setBackground(new java.awt.Color(204, 204, 204));
        ta8.setColumns(1);
        ta8.setFont(new java.awt.Font("Monospaced", 0, 3)); // NOI18N
        ta8.setRows(1);
        ta8.setTabSize(1);
        jScrollPane5.setViewportView(ta8);

        ta7.setEditable(false);
        ta7.setBackground(new java.awt.Color(204, 204, 204));
        ta7.setColumns(1);
        ta7.setFont(new java.awt.Font("Monospaced", 0, 3)); // NOI18N
        ta7.setRows(1);
        ta7.setTabSize(1);
        jScrollPane6.setViewportView(ta7);

        ta3.setEditable(false);
        ta3.setBackground(new java.awt.Color(204, 204, 204));
        ta3.setColumns(1);
        ta3.setFont(new java.awt.Font("Monospaced", 0, 3)); // NOI18N
        ta3.setRows(1);
        ta3.setTabSize(1);
        jScrollPane7.setViewportView(ta3);

        ta6.setEditable(false);
        ta6.setBackground(new java.awt.Color(204, 204, 204));
        ta6.setColumns(1);
        ta6.setFont(new java.awt.Font("Monospaced", 0, 3)); // NOI18N
        ta6.setRows(1);
        ta6.setTabSize(1);
        jScrollPane8.setViewportView(ta6);

        ta5.setEditable(false);
        ta5.setBackground(new java.awt.Color(204, 204, 204));
        ta5.setColumns(1);
        ta5.setFont(new java.awt.Font("Monospaced", 0, 3)); // NOI18N
        ta5.setRows(1);
        ta5.setTabSize(1);
        jScrollPane9.setViewportView(ta5);

        ta4.setEditable(false);
        ta4.setBackground(new java.awt.Color(204, 204, 204));
        ta4.setColumns(1);
        ta4.setFont(new java.awt.Font("Monospaced", 0, 3)); // NOI18N
        ta4.setRows(1);
        ta4.setTabSize(1);
        jScrollPane10.setViewportView(ta4);

        ta1.setEditable(false);
        ta1.setBackground(new java.awt.Color(204, 204, 204));
        ta1.setColumns(1);
        ta1.setFont(new java.awt.Font("Monospaced", 0, 3)); // NOI18N
        ta1.setRows(1);
        ta1.setTabSize(1);
        jScrollPane11.setViewportView(ta1);

        ta2.setEditable(false);
        ta2.setBackground(new java.awt.Color(204, 204, 204));
        ta2.setColumns(1);
        ta2.setFont(new java.awt.Font("Monospaced", 0, 3)); // NOI18N
        ta2.setRows(1);
        ta2.setTabSize(1);
        jScrollPane12.setViewportView(ta2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jScrollPane6)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
            .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea ta1;
    private javax.swing.JTextArea ta10;
    private javax.swing.JTextArea ta11;
    private javax.swing.JTextArea ta12;
    private javax.swing.JTextArea ta2;
    private javax.swing.JTextArea ta3;
    private javax.swing.JTextArea ta4;
    private javax.swing.JTextArea ta5;
    private javax.swing.JTextArea ta6;
    private javax.swing.JTextArea ta7;
    private javax.swing.JTextArea ta8;
    private javax.swing.JTextArea ta9;
    // End of variables declaration//GEN-END:variables
}
